### PR TITLE
Release 60

### PR DESCRIPTION
**Pull request by chimosky**
@quozl kindly review.

### CODE REVIEW

**Comment by chimosky** [comment]
Uploaded activity image to `/srv/activity-v4/bundles`, couldn't upload source file and also couldn't run `rebuild-aslo` as I don't have permissions to.

**Comment by quozl** [comment]
@srevinsaju, what access is needed on sunjammer to run rebuild-aslo?

@chimosky, I've
* merged,
* generated .xo and uploaded,
* generated .tar.bz2 and uplaoded,
* run `rebuild-aslo`.

**Comment by srevinsaju** [comment]
> @srevinsaju, what access is needed on sunjammer to run rebuild-aslo?

The activity maintainer must be a member of the `sugardl` group.

> 
> @chimosky, I've
> 
> * merged,
> * generated .xo and uploaded,
> * generated .tar.bz2 and uploaded,
> * run `rebuild-aslo`.

Agreed, this method looks right.

**Comment by srevinsaju** [comment]
It would be interesting to read the `rebuild-aslo` script to debug whats happening under the hood
```bash
cat `which rebuild-aslo`
```

**Comment by chimosky** [comment]
> @chimosky, I've
> 
>     * merged,
> 
>     * generated .xo and uploaded,
> 
>     * generated .tar.bz2 and uploaded,
> 
>     * run `rebuild-aslo`.

Thanks.

> ibiamchihurumnaya is a member of the sugardl group.

Confirmed. 

> @chimosky, what was the error?

`Sorry, user ibiamchihurumnaya is not allowed to execute '/usr/local/bin/rebuild-aslo' as root on sunjammer.sugarlabs.org.`

> It would be interesting to read the `rebuild-aslo` script to debug whats happening under the hood

Took a look and everything seems normal.

**Comment by srevinsaju** [comment]
@chimosky thanks for the error message. I have updated some policies. Can you retry running `rebuild-aslo` on sunjammer again?

**Comment by chimosky** [comment]
> @chimosky thanks for the error message. I have updated some policies. Can you retry running `rebuild-aslo` on sunjammer again?

Ran it again and I still get the same error.

**Comment by quozl** [comment]
When I `su` to root then to `ibiamchihurumnaya` and run `rebuild-aslo`, the result is

```log
[sudo] password for ibiamchihurumnaya: 
```

So the `NOPASSWD` in `/etc/sudoers.d/50-v4-activities` are not used.

When I am `quozl` and run `rebuild-aslo`, my guess is that my membership of the _admin_ group (a) avoids the password prompt, and (b) permits execution.

It looks like `/etc/sudoers.d/50-v4-activities`  needs an entry to allow `NOPASSWD` execution of `/srv/activities-v4/bin/aslo-rebuild`.

**Comment by chimosky** [comment]
> When I `su` to root then to `ibiamchihurumnaya` and run `rebuild-aslo`, the result is
> 
> ```
> [sudo] password for ibiamchihurumnaya: 
> ```
> 
> So the `NOPASSWD` in `/etc/sudoers.d/50-v4-activities` are not used.
> 
> When I am `quozl` and run `rebuild-aslo`, my guess is that my membership of the _admin_ group (a) avoids the password prompt, and (b) permits execution.
> 
> It looks like `/etc/sudoers.d/50-v4-activities` needs an entry to allow `NOPASSWD` execution of `/srv/activities-v4/bin/aslo-rebuild`.

Most likely, I can't see the contents of `/etc/sudoers.d/50-v4-activities` as I don't have that access.

**Comment by quozl** [comment]
@srevinsaju, what do you recommend?

**Comment by srevinsaju** [comment]
Ok fixed it now. I `su - ` as `ibiamchihurumnaya` and have run `rebuild-aslo`. Now it no longer asks for password. Kindly confirm.

**Comment by chimosky** [comment]
Thanks, I can now run `rebuild-aslo`.

**Comment by quozl** [comment]
Great.

**Pull request merged**
