### PR TITLE
port to python3 [WIP]

### PR DESCRIPTION
**Pull request by pidddgy**
.

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Please fix the TODO?

**Comment by srevinsaju** [comment]
@quozl, the variable @pidddgy has used is the right variable. So, i guess nothing else is to be done. Please review

**Comment by pidddgy** [comment]
`dbus.gobject_service.ExportedGObject` still needs to be ported to CollabWrapper, among other things like running 2to3

**Comment by tchx84** [comment]
@pidddgy @srevinsaju any time left to push this forward? If not let me know, so I can help.

This is the last python2 activity from our Flatpak collection :) and will unblock a few things for that project.

**Comment by walterbender** [comment]
As I recall, the block involved the SVG contortions I went through in importing artwork for custom mode. I think we could drop custom mode as I don't think it ever actually gets used.

**Comment by srevinsaju** [comment]
@tchx84 If the port to collabwrapper can be omitted, then this shoul finish quickly

**Comment by chimosky** [comment]
Didn't mean to close this PR but reopened as #16.

**Comment by pidddgy** [comment]
i'm not actively working on this right now, if anyone else wants to pick it up that'd be appreciated :)

**Comment by quozl** [comment]
@pidddgy, thanks for letting us know.

**Pull request closed without merging**
