### PR TITLE
Update metadata | Add COPYING files

### PR DESCRIPTION
**Pull request by vipulgupta2048**
@quozl @walterbender I don't know if there is a discrepancy or what but there are two files by the same name going by `dimensions.py` and `Dimensions.py`. Just letting you know, keeping a sharp eye about files. 

Fixed the address in `dimensions.py`
Deleted a LICENSE file.
Added a COPYING file for MIT to fix the multiple scenarios
Build runs with 0 errors. 
Updated .gitignore

### CODE REVIEW

**Comment by quozl** [comment]
Thanks @vipulgupta2048.  Reviewed to ce2ddad.

* [ ] you've correctly removed "Lesser General Public License" from `dimensions.py` (the license in the code had text from two different licenses) but you're not the copyright owner, so we'll need @walterbender to consent,
* [ ] repository metadata is incorrect, and;
* [ ] COPYING.MIT has omitted joint copyright owner Playful Invention Company.

**Comment by vipulgupta2048** [comment]
Fixed all and pinged Walter.

**Comment by vipulgupta2048** [comment]
What to now? Should we remove Playful Invention's copyright from everywhere and enforce GPLv3 everywhere?? 

Ps. @quozl I have tested all current open PRs with recursive and pushed changes for them. I have further decided to correct my error, and fix as many activities as i could. When I am done with my current cycle for the week.

**Comment by quozl** [comment]
@vipulgupta2048, perhaps you've over-reacted.  To paraphrase @walterbender; the files other than `sprites.py` should not have Playful Invention as copyright holder (and they don't, so that's good), but should be copyright Walter Bender and be GPLv3+ (which they do, except `dimensions.py` which has a mixed license text).

Note the embedded library `cairoplot` has copyright by others, and is LGPLv2+.

So the changes needed now are;
* [ ] revert your change to MIT for the license of `dimensions.py`, and instead change just the second paragraph of the license, which you can copy from `Dimensions.py`,
* [ ] add LGPLv2+ to license in metadata,
* [ ] do **not** add COPYING.LGPLv2+ for cairoplot, as it already has COPYING in that directory,

**Pull request merged**
